name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Run Deploy
    runs-on: ubuntu-latest
    env:
      HEROKU: ${{ secrets.HEROKU_STAGING_API_KEY }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - run: apt-get install -y ruby-dev
      - run: gem install dpl
      - run: dpl --provider=heroku --app=github-ci-cours --api-key=HEROKU
